sudo: "required"
dist: "trusty"
language: "python"
python: "3.5"
cache: "pip"
before_install:
  # Installing Czech LOCALE - https://docs.travis-ci.com/user/common-build-problems/#System%3A-Required-language-pack-isn%E2%80%99t-installed
  - sudo apt-get update
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-cs
script:
  - "blog lint"
env:
  global:
    - secure: "Tz6NlnhZoEbdb5yYUUlS6vJUCl7RK55UDMw1izZxI4XwS4fANxUh6q0YmhKcd7ysoCkeq4dz97XXdK/NfuM9ORGcljEA4A5yxPBj1ZZ+gcjhRBMdowJTsIermuSQk48QKEmIr/VpgFACSBqzI2hxzmt6+iuCT0/RTZKFykpayCs+7/Y7OiVXaGB2S8a1RbMjBThO2+U2/yJS0KXnfJgKfKOo8yx5CE2nfYvJJ1KpqH6Fxnhrh/0TUKco2T1jhyJe+zBa8Zh11USCN/+5LWemxXI2Jx+QKWPAh2G28PigIKZdx4JHqK3zpjT/eElFXwRMqQI6Lidk7XHP9U0E+Fha1F41kZAi2PjDERY2LwoJ8Y8ZH+nNYQGtzCkwugz4FoVe0gPHYxAM6ztrCwqB/cFmnAnIHwWNceWiOoKaTQYyHrAedRxaMR5uAH+pTeNBrSX6j5IZTuZ1YUdbuPkrFW/iFZHkhEsQUec9L39xlkCOp1861lA25xoHqclyhRfHjHl9kUXzNcM0zRMlZNZbEI8pu2iEqsYsuIp730A5MqAl67gW5C6O50g2tflIvDFZygVecdq1KmiaOVrFOwnvEbuTEezPBYlqHukkCGH2c4VBV1Z+GVY91LDVrUvggN+mtH1PmRbx68za2u2t9J6DGX2IBJbYLZhXINrXXXN4gD6LWFU="
deploy:
  provider: "script"
  script: "blog deploy"
  on:
    branch: "master"
    repo: "pyvec/blog.python.cz"
