sudo: "required"
dist: "trusty"
language: "python"
python: "3.5"
cache: "pip"
before_install:
  # Installing Czech LOCALE - https://docs.travis-ci.com/user/common-build-problems/#System%3A-Required-language-pack-isn%E2%80%99t-installed
  - sudo apt-get update
  - sudo apt-get --reinstall install -qq language-pack-en language-pack-cs
script:
  - "blog lint"
env:
  global:
    - secure: "B8pJ+YJZqi71fBkl68KJ3yRvA3ThCr99eT5vX5e/xGsh5uVjohWv0xHdINtdyuicwxDHp4cKOx+fx7aJp9YvFwoOHwzFAP2Soxe+aVEVvshWynSbgvcEBccXBFkf/UUF4UjsfjeegrOuwPGvKAhCXt1qN7GpxHFdzD/+TgOC2BL81kWGUheYFuOBtmhn5SaERHqorGRjMkXnBazr/nWVGN53qUdxj4y7EFALTvMo0+4heiMGdcra4V7XcE4p/KAYEB5cCvNf8g8tZdG53u/dgKJV4c+dnaJ/YDgBEt2lFkQBl1l7bITmZwRfTkIPh/A7wGv6Wa+PDizPHHxOWuhp+rB/cHRACPWr2/eXvX206xze4hcjp6JjMNp9ZXCL89ecxVFtkLDf2fT6R6/brglzU5vyKykvKKsCS4op2ZRkSb0RZSwDg6eLAFiv/uv02bY4aOFf8l5OxxIc6nMEEo+sdBbp2URHqcIXIDIqylZcSy2BqatSLRoTHoGBsmyer+KxlYYLFD+ZDO9RVp7DfTataa4USQk5tWsuyGJq9CpiZVbMm5QOeSueUIRaMf5FC1dqqQ4R8MTcfKEVJrD4LyXGqwinC/3aynLxmD20MoHOg0mDaOIFHGFQKVhco/Y+tMtkcArvRHkvxwgDTyq+YCX7PaMISFqpqStd4P7mE0DNymg="
deploy:
  provider: "script"
  script: "blog deploy"
  on:
    branch: "master"
    repo: "pyvec/blog.python.cz"
